Documentation and new algorithm
dhoehna/MazeAlgorithms pull request #1
Opened 2017-07-01 19:27 UTC by AUnderwood9

Added in-line documentation to Program, Grid, Room, Generator, RoomHelper, Binary, and Sidewinder classes. Implemented the Sidewinder algorithm in the Sidewinder class. And added a User input operation to choose between the two algorithm types in the Program class.

2017-07-02 00:48 UTC, dhoehna commented on CSharp/Mazes/Grid/Grid.cs
> +/*
Use /// notation for comments.  

Remove the part about the 2D array.  People can see that I am using a 2D array from the code.

Move the description to `public sealed class Grid`  and not at the namespace level.

2017-07-02 00:53 UTC, dhoehna commented on CSharp/Mazes/Grid/Grid.cs
> +        /*
Use /// for method comments.

Don't talk about RoomHelper here.  Move the comment to RoomHelper.  Remove the sentence with `starts out as null`.  People can see from the code that roomToConnect with is null and you don't need to explain it again.  

Method level comments should explain what it does, not the how.

2017-07-02 01:28 UTC, dhoehna requested changes

2017-07-02 01:28 UTC, dhoehna commented on CSharp/Mazes/Grid/Room.cs
> +        public int distance { get; set; }
Remove the extra space.

2017-07-02 01:28 UTC, dhoehna commented on CSharp/Mazes/Grid/Room.cs
> +        // Keeps track of the neighbors of said room to create a linked list type structure
use /// notation to comment properties.  Remove `...to create` and everything after.  Two reasons

1. What happens if I change what datatype I'm using
2. Linked List is not a structure
3. That part does not help explain why the Dictionary is there.

2017-07-02 01:28 UTC, dhoehna commented on CSharp/Mazes/Grid/Room.cs
> +        // Constructor
Use /// for method level comments.

2017-07-02 01:28 UTC, dhoehna commented on CSharp/Mazes/Grid/Room.cs
> +            // The direction of the room is the key.
This comment repeats what the code says.  Please remove it.

2017-07-02 01:28 UTC, dhoehna commented on CSharp/Mazes/Grid/RoomHelper.cs
> +            // move up a column
NIT: Can't move up a column.  Move right instead.

2017-07-02 01:28 UTC, dhoehna commented on CSharp/Mazes/Grid/RoomHelper.cs
> +        // This method finds all of the boundaries that each room is on. For example if a room is on the northern wall then it will have a boundary to the north
Please use /// for method level comments.

2017-07-02 01:28 UTC, dhoehna commented on CSharp/Mazes/MazeAlgorithms/Binary.cs
> +/*
Use /// to describe a class.  Please move this to above the class deceleration, not the namespace.

2017-07-02 01:28 UTC, dhoehna commented on CSharp/Mazes/MazeAlgorithms/Sidewinder.cs
> +    public class Sidewinder : IMazeAlgorithm
Add a  /// comment here to describe the class.

2017-07-02 01:28 UTC, dhoehna commented on CSharp/Mazes/MazeAlgorithms/Sidewinder.cs
> +            NORTH = Direction.NORTH,
Good job. :)

2017-07-02 01:28 UTC, dhoehna commented on CSharp/Mazes/MazeGenerator/Generator.cs
> +        // The algorithm that is used to create the rooms is applied here.
Use /// for comments describing a method.

2017-07-02 01:28 UTC, dhoehna commented on CSharp/Mazes/Mazes/Program.cs
> +            int algoType;
NIT: `algorithmType` not `algoType` The first is more clear.

2017-07-02 01:28 UTC, dhoehna commented on CSharp/Mazes/Mazes/Program.cs
> +            IMazeAlgorithm currentAlgorithm;
Nice job on finding a way to continually ask for the correct input.

2017-07-02 01:28 UTC, dhoehna commented on CSharp/Mazes/Mazes/Program.cs
> +                        currentAlgorithm = null;
NIT: Make currentAlgortihm null when you declare it, so you don't have to re-declare it here.

2017-07-06 01:26 UTC, AUnderwood9 commented on CSharp/Mazes/Grid/Room.cs
> +        // Constructor
Removed this comment. It is not needed.

2017-07-06 01:47 UTC, AUnderwood9 commented
I have addressed the issues presented here and pushed them to the branch to be merged.

2017-07-10 04:07 UTC, dhoehna approved these changes

2017-07-10 04:08 UTC, merged